---
##################
# BEGIN TEMPLATE #
##################
kind: "Template"
apiVersion: "v1"
metadata:
  name: "s3cmd"
  annotations:
    description: "S3CMD tool"
    tags: "kermit"
labels: 
  template: "s3cmd"
objects:
###################
# Layer 0: Images #
###################
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: alpine
    labels:
      app: ${APPLICATION_NAME}
  spec:
    tags:
    - name: "3.3"
      from:
        kind: DockerImage
        name: docker.io/alpine
########################
### Layer 1: Builds ####
########################
- kind: "BuildConfig"
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
      annotations: 
        description: "Defines how to build the application"
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/orangekmt/docker-s3cmd.git"
    strategy:
      type: "Docker"
      dockerStrategy:
        from:
          kind: "ImageStreamTag"
          name: "alpine:3.3"
    output:
      to:
        kind: "ImageStreamTag"
        name: "${APPLICATION_NAME}:latest"
    triggers:
      - type: "ImageChange"
      - type: "ConfigChange"
###################
# Layer 2: Images #
###################
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      description: "Resulting Docker Image after the buit of s3cmd."
  spec:
    tags:
      -
        tag: latest
########################
# Layer 3: Deployments #
########################
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      name: "${APPLICATION_NAME}"
  spec:
    strategy: 
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
    triggers:
      -
        type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: ImageStreamTag
            name: ${APPLICATION_NAME}:latest
      -
        type: ConfigChange
    replicas: 1
    test: false
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    template:
      metadata:
        name: ${APPLICATION_NAME}
        labels: 
          deploymentConfig: ${APPLICATION_NAME}
      spec:
        containers:
        - image: "${APPLICATION_NAME}"
          name: "${APPLICATION_NAME}"
          ports:
          - containerPort: 8080
          env:
          - name: "aws_key"
            value: "${ACCOUNT_KEY}"
          - name: "aws_secret"
            value: "${ACCOUNT_SECRET}"
          - name: "cmd"
            value: "${OPERATION}"
          - name: "s3_host_base"
            value: "${S3_SERVER_HOST}"
          - name: "s3_host_bucket"
            value: "s3://${S3_BUCKET_NAME}.${S3_SERVER_HOST}"	
            terminationMessagePath: "/dev/termination-log"
            imagePullPolicy: Always
            securityContext:
              capabilities: {}
              privileged: false		
        restartPolicy: "Always"
        terminationGracePeriodSeconds: 30
        dnsPolicy: "ClusterFirst"
# +++++++++++++++++++++++++++++++++
# ++++++ LAYER 4 ABSTRACTIONS +++++
# +++++++++++++++++++++++++++++++++
- apiVersion: v1
  kind: Service
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      description: "Exposes and load balances the application pods."
  spec:
    ports:
      -
        name: "http"
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      deploymentConfig: "${APPLICATION_NAME}"
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
      network: ${PUBLIC_NETWORK}
    annotations:
      description: "The route exposes the service with an hostname."
  spec:
    host: "${APPLICATION_HOSTNAME}"
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
    port:
      targetPort: 8080
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow
##############
# Parameters #
##############
parameters:
- name: APPLICATION_NAME
  displayName: "Application name"
  description: "The name assigned to all of the objects defined in this template."
  required: true
  value: "s3cmd"
- name: "APPLICATION_HOSTNAME"
  displayName: "Application hostname"
  description: "The hostname for exposing your application on the Internal Network (*.kermit.itn.intraorange) or on the Internet (*.kmt.orange.com)."
- name: "PUBLIC_NETWORK"
  displayName: "Application exposed on Internet Flag"
  description: "If your application will be exposed on the Internet (HOSTNAME = *.kmt.orange.com) you need to setup this flag with the value: public"
- name: ACCOUNT_KEY
  displayName: "S3 Server Account Key"
  description: "The key value used for user authentication to the S3 Server."
  required: true
  value: kermit-prod
- name: ACCOUNT_SECRET
  displayName: "S3 Server Account Secret"
  description: "The secret value used for password authentication to the S3 Server."
  required: true
- name: S3_SERVER_HOST
  displayName: "S3 Server hostname"
  description: "The hostname of the S3 Server."
  required: true
  value: storage.orange.com
- name: S3_BUCKET_NAME
  displayName: "S3 Server bucket"
  description: "The bucket name within the S3 Server."
  required: true
  value: s3cmd-test
- name: OPERATION
  displayName: "Operation"
  description: "The operation type that you want to perform. (sync-local-to-s3 / sync-s3-to-local)"
  required: true
  value: sync-local-to-s3
